version: '3.8'

services:
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/db
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
      SPRING_MAIL_USERNAME: something@email.com
      SPRING_MAIL_PASSWORD: abc
    depends_on:
      - database
      
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mysql_data:
