name: Server Deploy

on:
  workflow_run:
    workflows: ["Server Build"]
    types:
      - completed

jobs:

  pull:
    runs-on: self-hosted
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
      SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
    steps:
    - name: Pull Docker Image
      run: sudo docker pull skmahajan4998/opus-app:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f opus-app-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 -e SPRING_DATASOURCE_URL=${DB_URL} -e SPRING_DATASOURCE_USERNAME=${DB_USERNAME} -e SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} -e SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME} -e SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD} --name opus-app-container skmahajan4998/opus-app
