name: Server Integration

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server/
    env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
        SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build Project
      run: mvn clean install \
        -D spring.datasource.url=${DB_URL} \
        -D spring.datasource.username=${DB_USERNAME} \
        -D spring.datasource.password=${DB_PASSWORD} \
        -D spring.jpa.show-sql=true \
        -D spring.flyway.baseline-on-migrate=true \
        -D spring.flyway.locations=classpath:db/migration \
        -D spring.mail.host=smtp.gmail.com \
        -D spring.mail.port=587 \
        -D spring.mail.username=${SPRING_MAIL_USERNAME} \
        -D spring.mail.password=${SPRING_MAIL_PASSWORD} \
        -D spring.mail.properties.mail.smtp.auth=true \
        -D spring.mail.properties.mail.smtp.starttls.enable=true \
        -B

